language: objective-c
osx_image: xcode8.3

before_install:
  - pod repo update --silent
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace QuotesIOS.xcworkspace -scheme 'QuotesIOS' -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test CODE_SIGN_IDENTITY=- | xcpretty -c
